language: node_js
cache:
  directories:
  - "~/.npm"
node_js:
- 17.9.1
before_install:
- openssl aes-256-cbc -K $encrypted_2d8c63ef40a5_key -iv $encrypted_2d8c63ef40a5_iv
  -in id_rsa.enc -out ../id_rsa -d
- chmod 600 ../id_rsa
- echo -e "Host $DEPLOY_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
install:
- npm install
script:
- npm run build
- cp Dockerfile dist/
- tar -czf blog-frontend.tgz dist/
after_success:
  - scp -i ../id_rsa blog-frontend.tgz $DEPLOY_USER@$DEPLOY_SERVER:~
  - ssh -i ../id_rsa $DEPLOY_USER@$DEPLOY_SERVER 'mkdir -p blog-frontend && tar xzf blog-frontend.tgz -C blog_frontend && cd blog_frontend && docker build -t blog-frontend .
  #&& kind load docker-image blog-frontend && kubectl apply -f kubernetes-manifests/ && rm -rf blog-frontend.tgz && rm -rf dist && rm -rf Dockerfile'