language: node_js

node_js:
  - 17.9.1 # 19.x Ubuntu 16.04.7 version issue

cache:
  npm: true
  directories:
    - "~/.npm"
    - "~/.cache"
    - "node_modules"

before_install:
  - npm config set registry https://registry.npmjs.org/
  - npm install -g npm@8.11.0

install:
  - npm install

script:
  - npm run build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_2d8c63ef40a5_key -iv $encrypted_2d8c63ef40a5_iv -in id_rsa.enc -out ../id_rsa -d
  - chmod 600 ../id_rsa
  - echo -e "Host $DEPLOY_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main
    #travis encrypt-file ../id_rsa --add --com
# argocd app sync blog-frontend
