const PlaygroundEditorTheme = {
  ltr: "PlaygroundEditorTheme__ltr",
  rtl: "PlaygroundEditorTheme__rtl",
  placeholder: "PlaygroundEditorTheme__placeholder",
  paragraph: "PlaygroundEditorTheme__paragraph",
  quote: "PlaygroundEditorTheme__quote",
  heading: {
    h1: "PlaygroundEditorTheme__h1",
    h2: "PlaygroundEditorTheme__h2",
    h3: "PlaygroundEditorTheme__h3",
    h4: "PlaygroundEditorTheme__h4",
    h5: "PlaygroundEditorTheme__h5",
  },
  list: {
    nested: {
      listitem: "PlaygroundEditorTheme__nestedListItem",
    },
    ol: "PlaygroundEditorTheme__ol1",
    ol2: "PlaygroundEditorTheme__ol2",
    ol3: "PlaygroundEditorTheme__ol3",
    ol4: "PlaygroundEditorTheme__ol4",
    ol5: "PlaygroundEditorTheme__ol5",
    ul: "PlaygroundEditorTheme__ul",
    listitem: "PlaygroundEditorTheme__listItem",
    listItemChecked: "PlaygroundEditorTheme__listItemChecked",
    listItemUnchecked: "PlaygroundEditorTheme__listItemUnchecked",
  },
  image: "PlaygroundEditorTheme__image",
  link: "PlaygroundEditorTheme__link",
  text: {
    bold: "PlaygroundEditorTheme__textBold",
    italic: "PlaygroundEditorTheme__textItalic",
    overflowed: "PlaygroundEditorTheme__textOverflowed",
    hashtag: "PlaygroundEditorTheme__hashtag",
    underline: "PlaygroundEditorTheme__textUnderline",
    strikethrough: "PlaygroundEditorTheme__textStrikethrough",
    underlineStrikethrough: "PlaygroundEditorTheme__textUnderlineStrikethrough",
    code: "PlaygroundEditorTheme__textCode",
    subscript: "PlaygroundEditorTheme__textSubscript",
    superscript: "PlaygroundEditorTheme__textSuperscript",
    highlight: "PlaygroundEditorTheme__mark",
  },
  code: "PlaygroundEditorTheme__code",
  codeHighlight: {
    atrule: "PlaygroundEditorTheme__tokenAttr",
    attr: "PlaygroundEditorTheme__tokenAttr",
    boolean: "PlaygroundEditorTheme__tokenProperty",
    builtin: "PlaygroundEditorTheme__tokenSelector",
    cdata: "PlaygroundEditorTheme__tokenComment",
    char: "PlaygroundEditorTheme__tokenSelector",
    class: "PlaygroundEditorTheme__tokenFunction",
    "class-name": "PlaygroundEditorTheme__tokenFunction",
    comment: "PlaygroundEditorTheme__tokenComment",
    constant: "PlaygroundEditorTheme__tokenProperty",
    deleted: "PlaygroundEditorTheme__tokenProperty",
    doctype: "PlaygroundEditorTheme__tokenComment",
    entity: "PlaygroundEditorTheme__tokenOperator",
    function: "PlaygroundEditorTheme__tokenFunction",
    important: "PlaygroundEditorTheme__tokenVariable",
    inserted: "PlaygroundEditorTheme__tokenSelector",
    keyword: "PlaygroundEditorTheme__tokenAttr",
    namespace: "PlaygroundEditorTheme__tokenVariable",
    number: "PlaygroundEditorTheme__tokenProperty",
    operator: "PlaygroundEditorTheme__tokenOperator",
    prolog: "PlaygroundEditorTheme__tokenComment",
    property: "PlaygroundEditorTheme__tokenProperty",
    punctuation: "PlaygroundEditorTheme__tokenPunctuation",
    regex: "PlaygroundEditorTheme__tokenVariable",
    selector: "PlaygroundEditorTheme__tokenSelector",
    string: "PlaygroundEditorTheme__tokenSelector",
    symbol: "PlaygroundEditorTheme__tokenProperty",
    tag: "PlaygroundEditorTheme__tokenProperty",
    url: "PlaygroundEditorTheme__tokenOperator",
    variable: "PlaygroundEditorTheme__tokenVariable",
  },
  table: {
    table: "PlaygroundEditorTheme__table",
    tableCell: "PlaygroundEditorTheme__tableCell",
    tableCellHeader: "PlaygroundEditorTheme__tableCellHeader",
    tableCellSelected: "PlaygroundEditorTheme__tableCellSelected",
    tableCellPrimarySelected: "PlaygroundEditorTheme__tableCellPrimarySelected",
    tableCellEditing: "PlaygroundEditorTheme__tableCellEditing",
    tableAddColumns: "PlaygroundEditorTheme__tableAddColumns",
    tableAddRows: "PlaygroundEditorTheme__tableAddRows",
    tableCellResizer: "PlaygroundEditorTheme__tableCellResizer",
    tableCellActionButtonContainer:
      "PlaygroundEditorTheme__tableCellActionButtonContainer",
    tableCellActionButton: "PlaygroundEditorTheme__tableCellActionButton",
  },
  characterLimit: "PlaygroundEditorTheme__characterLimit",
  embedBlock: "PlaygroundEditorTheme__embedBlock",
  embedBlockFocus: "PlaygroundEditorTheme__embedBlockFocus",
  layoutContainer: "PlaygroundEditorTheme__layoutContainer",
  layoutItem: "PlaygroundEditorTheme__layoutItem",
  autocomplete: "PlaygroundEditorTheme__autocomplete",
  horizontalRule: "PlaygroundEditorTheme__hr",
};

export default PlaygroundEditorTheme;
